<a href="https://colab.research.google.com/github/Shivani7122/DSA-WITH-PYTHON/blob/main/NUMPY_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
'''import numpy
import numpy as np
from numpy import *'''

'import numpy \nimport numpy as np\nfrom numpy import *'

In [ ]:
from numpy import *


In [ ]:
val = array ([1,2,3,4.6])

In [ ]:
for num in val:
  print(num, end= " ")

1.0 2.0 3.0 4.6 

Numpy helps to store Heterogeneous elements


In [ ]:
h1 = array([1,2,3,4,6], float)
for num in h1:
  print(num,end=" ")

1.0 2.0 3.0 4.0 6.0 

In [ ]:
h2 = array([1,2,3,4.6], int)
for num in h2:
  print(num,end=" ")

1 2 3 4 

ARITHMENTIC PROGRESSION ON ARRAY

In [ ]:
#Partition------------ divide the number in specified parts
ab = linspace(10,20,3)
for a in ab:
  print(a,end =" ")

10.0 15.0 20.0 

In [ ]:
#arange()-----------common difference ap
au = arange(10,20,3)
for x in au:
  print(x, end = " ")

10 13 16 19 

In [ ]:
#logspace()-----commom diff is in log
au = logspace(10,20,2)
for x in au:
  print(x, end = " ")


10000000000.0 1e+20 

In [ ]:
#zeros()-------make array of zeroes
val = zeros(5)
for s in val:
  print(s,end=" ")

0.0 0.0 0.0 0.0 0.0 

In [ ]:
#ones()-------make array of one
val = ones(6)
for s in val:
  print(s, end = " ")

1.0 1.0 1.0 1.0 1.0 1.0 

In [ ]:
#full()-----------for numbers other than 0's or 1's

val = full(5,4)
for s in val:
  print(s, end = " ")

4 4 4 4 4 

# **MULTI-DIMENSIONAL** **ARRAY**



In [ ]:
from numpy import*

In [ ]:
zero = array(10)
print(zero)

10


In [ ]:
one = array([1,2,3,4,5])
print(one)

[1 2 3 4 5]


In [ ]:
two = array([[1,2,3],[4,5,6],[7,8,9]])
print(two)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
 three = array([[[1,2,3],[4,5,6],[7,8,9]],[[2,4,6],[8,10,12],[3,6,9]]])
 print(three)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 3  6  9]]]
